name: fittor
description: A comprehensive Flutter package for creating responsive UIs that adapt to different screen sizes and orientations.
version: 1.0.4
repository: https://github.com/mushthakvp/fittor
issue_tracker: https://github.com/mushthakvp/fittor/issues
license: MIT

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/no_internet.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

